name: Customers Basic

on:
  workflow_dispatch:
  push:
    paths:
      - customers-basic/**
    branches:
      - '**'

jobs:
  common:
    uses: ./.github/workflows/common.yml
  build:
    name: Build
    needs: common
    runs-on: ubuntu-latest
    env:
      working-directory: ./customers-basic
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-customers-basic
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          cd ../common && mvn clean install
          ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME